t2n_plotChannel(neuron,'gbar_na8st','soma','channelPlots');close all
t2n_plotChannel(neuron,'gkbar_Kv11','','channelPlots','-si10');close all
t2n_plotChannel(neuron,'gkbar_Kir21','','channelPlots','-h');close all
t2n_plotChannel(neuron,'gbar_HCN','','channelPlots','-h');close all
t2n_plotChannel(neuron,'gkbar_Kv14','','channelPlots','');close all
t2n_plotChannel(neuron,'gkbar_Kv21','','channelPlots','-si5');close all
t2n_plotChannel(neuron,'gkbar_Kv34','','channelPlots','');close all
t2n_plotChannel(neuron,'gkbar_Kv42','','channelPlots','');close all
t2n_plotChannel(neuron,'gkbar_Kv723','','channelPlots','-sa');close all
t2n_plotChannel(neuron,'gbar_Cav12','','channelPlots','-fa-si');close all
t2n_plotChannel(neuron,'gbar_Cav13','','channelPlots','-fa5');close all
t2n_plotChannel(neuron,'gbar_Cav22','','channelPlots','');close all
t2n_plotChannel(neuron,'gbar_Cav32','','channelPlots','');close all
t2n_plotChannel(neuron,'gakbar_BK','','channelPlots','');close all
t2n_plotChannel(neuron,'gabkbar_BK','','channelPlots','');close all